### ISSUE TITLE
Initial iterations for Bisection and ITP do work correctly

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaMath/Roots.jl#279] opened 2022-03-16 15:41 UTC
I have not tested other solvers. Lets start with the issue with ITP - the first and second iterations are the same:

```
julia> using Roots

julia> f(x) = x^2-2
f (generic function with 1 method)

julia> tracker1 = Roots.Tracks()
Algorithm has not been run

julia> find_zero(f, (0, 2), Roots.ITP(), tracks=tracker1)
1.4142135623730951

julia> tracker1
Results of univariate zero finding:

* Converged to: 1.4142135623730951
* Algorithm: Roots.ITP{Float64, Int64}(0.2, 2, 1)
* iterations: 12
* function evaluations ≈ 13
* stopped as x_n ≈ x_{n-1} using atol=xatol, rtol=xrtol

Trace:
(a_0, b_0) = ( 0.0000000000000000,  2.0000000000000000)
(a_1, b_1) = ( 0.0000000000000000,  2.0000000000000000)
(a_2, b_2) = ( 1.0000000000000000,  2.0000000000000000)
(a_3, b_3) = ( 1.0000000000000000,  1.5000000000000000)
(a_4, b_4) = ( 1.3499999999999999,  1.5000000000000000)
(a_5, b_5) = ( 1.3499999999999999,  1.4167807017543861)
(a_6, b_6) = ( 1.4132620498137980,  1.4167807017543861)
(a_7, b_7) = ( 1.4132620498137980,  1.4142151754357926)
(a_8, b_8) = ( 1.4142133801405712,  1.4142151754357926)
(a_9, b_9) = ( 1.4142133801405712,  1.4142135623736356)
(a_10, b_10) = ( 1.4142135623730883,  1.4142135623736356)
(a_11, b_11) = ( 1.4142135623730949,  1.4142135623736356)
(a_12, b_12) = ( 1.4142135623730949,  1.4142135623730951)

```

I think it is in all likelihood an error in the tracking, but should be fixed so as to not be misleading about what goes on.

Secondly, the bisection method. I will use an atol of 1e-8 for comparison purposes. Check out the start of that trace - it is absolutely bonkers, and not at all doing bisection until after iteration number 9:

```
julia> tracker2 = Roots.Tracks()
Algorithm has not been run

julia> find_zero(f, (0, 2), Roots.Bisection(), tracks=tracker2, atol=1e-8)
1.4142135605216026

julia> tracker2
Results of univariate zero finding:

* Converged to: 1.4142135679721832
* Algorithm: Bisection()
* iterations: 36
* function evaluations ≈ 39
* stopped as |f(x_n)| ≤ max(δ, |x|⋅ϵ) using δ = atol, ϵ = rtol

Trace:
(a_0, b_0) = ( 0.0000000000000000,  2.0000000000000000)
(a_1, b_1) = ( 0.0000000000000000,  2.0000000000000000)
(a_2, b_2) = ( 0.0000000000000000,  2.0000000000000000)
(a_3, b_3) = ( 0.0000000000000000,  2.0000000000000000)
(a_4, b_4) = ( 0.0000000004656613,  2.0000000000000000)
(a_5, b_5) = ( 0.0000305175781250,  2.0000000000000000)
(a_6, b_6) = ( 0.0078125000000000,  2.0000000000000000)
(a_7, b_7) = ( 0.1250000000000000,  2.0000000000000000)
(a_8, b_8) = ( 0.5000000000000000,  2.0000000000000000)
(a_9, b_9) = ( 1.0000000000000000,  2.0000000000000000)
(a_10, b_10) = ( 1.0000000000000000,  1.5000000000000000)
(a_11, b_11) = ( 1.2500000000000000,  1.5000000000000000)
(a_12, b_12) = ( 1.3750000000000000,  1.5000000000000000)
(a_13, b_13) = ( 1.3750000000000000,  1.4375000000000000)
(a_14, b_14) = ( 1.4062500000000000,  1.4375000000000000)
(a_15, b_15) = ( 1.4062500000000000,  1.4218750000000000)
(a_16, b_16) = ( 1.4140625000000000,  1.4218750000000000)
(a_17, b_17) = ( 1.4140625000000000,  1.4179687500000000)
(a_18, b_18) = ( 1.4140625000000000,  1.4160156250000000)
(a_19, b_19) = ( 1.4140625000000000,  1.4150390625000000)
(a_20, b_20) = ( 1.4140625000000000,  1.4145507812500000)
(a_21, b_21) = ( 1.4140625000000000,  1.4143066406250000)
(a_22, b_22) = ( 1.4141845703125000,  1.4143066406250000)
(a_23, b_23) = ( 1.4141845703125000,  1.4142456054687500)
(a_24, b_24) = ( 1.4141845703125000,  1.4142150878906250)
(a_25, b_25) = ( 1.4141998291015625,  1.4142150878906250)
(a_26, b_26) = ( 1.4142074584960938,  1.4142150878906250)
(a_27, b_27) = ( 1.4142112731933594,  1.4142150878906250)
(a_28, b_28) = ( 1.4142131805419922,  1.4142150878906250)
(a_29, b_29) = ( 1.4142131805419922,  1.4142141342163086)
(a_30, b_30) = ( 1.4142131805419922,  1.4142136573791504)
(a_31, b_31) = ( 1.4142134189605713,  1.4142136573791504)
(a_32, b_32) = ( 1.4142135381698608,  1.4142136573791504)
(a_33, b_33) = ( 1.4142135381698608,  1.4142135977745056)
(a_34, b_34) = ( 1.4142135381698608,  1.4142135679721832)
(a_35, b_35) = ( 1.4142135530710220,  1.4142135679721832)
(a_36, b_36) = ( 1.4142135605216026,  1.4142135679721832)
```

I can confirm that my own implementation converges after 29 iterations, as opposed to the current Root.Bisection's 36.

<details>

```
julia> results = xs = Tuple[(0, 2)]
1-element Vector{Tuple}:
 (0, 2)

julia> f(x) = x^2-2
f (generic function with 1 method)

julia> err = Inf
Inf

julia> while err > 1e-8
       # for _ in 1:100
           x_lim1, x_lim2 = xs[end]
           xm = (x_lim1 + x_lim2) / 2
           if sign(f(x_lim1)) == sign(f(xm))
               x_lim1_new = xm
               x_lim2_new = x_lim2
           else
               x_lim1_new = x_lim1
               x_lim2_new = xm
           end

           push!(results, (x_lim1_new, x_lim2_new))
           err = min(f(x_lim1_new)|>abs, f(x_lim2_new)|>abs)
       end

julia> results .|> println;
(0, 2)
(1.0, 2)
(1.0, 1.5)
(1.25, 1.5)
(1.375, 1.5)
(1.375, 1.4375)
(1.40625, 1.4375)
(1.40625, 1.421875)
(1.4140625, 1.421875)
(1.4140625, 1.41796875)
(1.4140625, 1.416015625)
(1.4140625, 1.4150390625)
(1.4140625, 1.41455078125)
(1.4140625, 1.414306640625)
(1.4141845703125, 1.414306640625)
(1.4141845703125, 1.41424560546875)
(1.4141845703125, 1.414215087890625)
(1.4141998291015625, 1.414215087890625)
(1.4142074584960938, 1.414215087890625)
(1.4142112731933594, 1.414215087890625)
(1.4142131805419922, 1.414215087890625)
(1.4142131805419922, 1.4142141342163086)
(1.4142131805419922, 1.4142136573791504)
(1.4142134189605713, 1.4142136573791504)
(1.4142135381698608, 1.4142136573791504)
(1.4142135381698608, 1.4142135977745056)
(1.4142135381698608, 1.4142135679721832)
(1.414213553071022, 1.4142135679721832)
(1.4142135605216026, 1.4142135679721832)
```

</details>

**Comment by jverzani** [comment] 2022-03-16 15:49
Yes, the reason is technical. The other initializations for bracketing methods first get both a and b to have the same sign, regardless of it being in the middle. (This is due to the middle used for Float64 which isn't simply (a+b)/2). So there is an initial step accounted for the default method. I should adjust that. Thanks for opening this issue.

**Comment by jverzani** [comment] 2022-03-19 22:30
In #280 this should be fixed *except* for the basic bisection method (which would require some reworking to get done due to the initialization of the state). If not, let me know. But am closing for now. Thanks for the feedback.

Now the bisection isn't bonkers, it is just doing things in the background! The bisection finds the middle after conversion to unsigned integers. This means when you start at  0, you get odd things, such as:

julia> a,b = 0.0, 1.0
(0.0, 1.0)

julia> a = Roots.__middle(a, b)
1.118751109680031e-154

julia> a = Roots.__middle(a, b)
1.0795210693868056e-77

julia> a = Roots.__middle(a, b)
3.3060778616876836e-39

julia> a = Roots.__middle(a, b)
5.759824041329242e-20
```

These just show as 0 to 16 decimal points, so the trace doesn't see them. (The advantage of using this notion of middle is bisection is guaranteed to take no more than 64 steps in float64, which isn't the case with `a+(b-a)/2` say.

**Closed by jverzani** 2022-03-19 22:30 UTC

**Comment by KronosTheLate** [comment] 2022-03-25 10:53
I still find the following trace to be quite problematic - as a normal user, it would really make be doubt the Tracks in general.
```
julia> using Roots

julia> f(x) = x^2-2
f (generic function with 1 method)

julia> find_zero(f, (0, 2), Bisection(), verbose=true)
Results of univariate zero finding:

* Converged to: 1.4142135623730951
* Algorithm: Roots.BisectionExact()
* iterations: 61
* function evaluations ≈ 64
* stopped as x_n ≈ x_{n-1} using atol=xatol, rtol=xrtol

Trace:
(a_0, b_0) = ( 0.0000000000000000,  2.0000000000000000 )
(a_1, b_1) = ( 0.0000000000000000,  2.0000000000000000 )
(a_2, b_2) = ( 0.0000000000000000,  2.0000000000000000 )
(a_3, b_3) = ( 0.0000000000000000,  2.0000000000000000 )
(a_4, b_4) = ( 0.0000000004656613,  2.0000000000000000 )
(a_5, b_5) = ( 0.0000305175781250,  2.0000000000000000 )
(a_6, b_6) = ( 0.0078125000000000,  2.0000000000000000 )
(a_7, b_7) = ( 0.1250000000000000,  2.0000000000000000 )
(a_8, b_8) = ( 0.5000000000000000,  2.0000000000000000 )
(a_9, b_9) = ( 1.0000000000000000,  2.0000000000000000 )
(a_10, b_10) = ( 1.0000000000000000,  1.5000000000000000 )
(a_11, b_11) = ( 1.2500000000000000,  1.5000000000000000 )
(a_12, b_12) = ( 1.3750000000000000,  1.5000000000000000 )
(a_13, b_13) = ( 1.3750000000000000,  1.4375000000000000 )
...
```

Would it be possible to band-aid / duct-tape fix it by modifying the trace after the root is found, only for bisection? By looking for the first iteration with interval width half of the previous interval width, and making the "previous" interval the first in the trace? Then, a proper fix could be added at a later point, if it is indeed more complicated.

**Comment by jverzani** [comment] 2022-03-25 11:20
The solution is not to use formatting by `printf` and rather, print the numbers with scientific notation. (But you aren't even seeing the more annoying part -- the first step is logged after initialization, which for bisection, which always does one "step" during initialization, will show the first step not the initial interval.

**Comment by KronosTheLate** [comment] 2022-03-25 11:30
If the problems run that deep, then would a different approach to logging be beneficial? Perhaps what NLSolve.jl does is more robust somehow?

**Comment by jverzani** [comment] 2022-03-25 11:46
They have:

```
@printf io "%6d   %14e   %14e\n" t.iteration t.fnorm t.stepnorm
```

Whereas, Roots currently uses:

```
 "%s = % 18.16f,\t %s = % 18.16f"
```

I think there is room for improvement there.

**Comment by jverzani** [comment] 2022-03-25 12:24
Okay, with that fix you see:

```
Trace:
(a_0, b_0) = ( 1.491668e-154,   2.000000e+00 )
(a_1, b_1) = (  1.727234e-77,   2.000000e+00 )
(a_2, b_2) = (  5.877472e-39,   2.000000e+00 )
(a_3, b_3) = (  1.084202e-19,   2.000000e+00 )
(a_4, b_4) = (  4.656613e-10,   2.000000e+00 )
(a_5, b_5) = (  3.051758e-05,   2.000000e+00 )
(a_6, b_6) = (  7.812500e-03,   2.000000e+00 )
```

That's better. **However** it finishes with:

```
(a_33, b_33) = (  1.414214e+00,   1.414214e+00 )
(a_34, b_34) = (  1.414214e+00,   1.414214e+00 )
(a_35, b_35) = (  1.414214e+00,   1.414214e+00 )
(a_36, b_36) = (  1.414214e+00,   1.414214e+00 )
(a_37, b_37) = (  1.414214e+00,   1.414214e+00 )
(a_38, b_38) = (  1.414214e+00,   1.414214e+00 )
(a_39, b_39) = (  1.414214e+00,   1.414214e+00 )
(a_40, b_40) = (  1.414214e+00,   1.414214e+00 )
(a_41, b_41) = (  1.414214e+00,   1.414214e+00 )
(a_42, b_42) = (  1.414214e+00,   1.414214e+00 )
(a_43, b_43) = (  1.414214e+00,   1.414214e+00 )
(a_44, b_44) = (  1.414214e+00,   1.414214e+00 )
(a_45, b_45) = (  1.414214e+00,   1.414214e+00 )
(a_46, b_46) = (  1.414214e+00,   1.414214e+00 )
(a_47, b_47) = (  1.414214e+00,   1.414214e+00 )
(a_48, b_48) = (  1.414214e+00,   1.414214e+00 )
(a_49, b_49) = (  1.414214e+00,   1.414214e+00 )
(a_50, b_50) = (  1.414214e+00,   1.414214e+00 )
(a_51, b_51) = (  1.414214e+00,   1.414214e+00 )
(a_52, b_52) = (  1.414214e+00,   1.414214e+00 )
(a_53, b_53) = (  1.414214e+00,   1.414214e+00 )
(a_54, b_54) = (  1.414214e+00,   1.414214e+00 )
(a_55, b_55) = (  1.414214e+00,   1.414214e+00 )
(a_56, b_56) = (  1.414214e+00,   1.414214e+00 )
(a_57, b_57) = (  1.414214e+00,   1.414214e+00 )
(a_58, b_58) = (  1.414214e+00,   1.414214e+00 )
(a_59, b_59) = (  1.414214e+00,   1.414214e+00 )
(a_60, b_60) = (  1.414214e+00,   1.414214e+00 )
(a_61, b_61) = (  1.414214e+00,   1.414214e+00 )
```

which is pretty unsatisfying. Need to think this through. With that change, every problem looks off, whereas with it as it is, only when 0 is encountered (which is often if the interval has different signs) and really large values. I'd guess there are settings with printf that would help here.

**Comment by KronosTheLate** [comment] 2022-03-25 16:43
I mean, the problem is not the formatting. It is the fact that internal changes to the interval are recorded, before bisection is applied, and then presented as a part of the bisection algorithm. Those first few lines, which do NOT have their interval width halved at each iteration, should not be there at all. It is not a matter of formatting, it is a matter of recording the wrong datapoints.

**Comment by jverzani** [comment] 2022-03-25 19:13
The issue is the tracks aren't precise. This was a design decision. We could avoid it here, by lugging around an extra two values in the state object, but that isn't very elegant, and doesn't seem worthwhile. The user knows what they started with, they know where they ended, and if curious can see how they got there. I suppose this could be better documented...

But you are correct in saying we should do a better job in displaying the values shown, as large and small values should be better accommodated.

What is also a design decision was to avoid interval halving in the basic bisection. This makes the algorithm more robust to certain allowable inputs at  little computational expense (though the user must know what to expect, namely, that the halving takes place at the bit level, not the decimal representation level.) 

To see that it is more robust, here is a simple algorithm to find pi with bisection. How many steps will it take:

```
function find_pi()
    f(x) = x - pi
    a,b = nextfloat(-Inf), prevfloat(Inf)
    fa, fb = f(a), f(b)
    c = a/2 + b/2 # (a+b)/2 and a + (b-a)/2 both can have overflow issues
    fc = f(c)
    cnt = 0
    while a < c < b

        if sign(fa) * sign(fc) < 0
            b,fb = c, fc
        else
            a, fa = c, fc
        end

        c = a + (b-a)/2
        fc = f(c)
        cnt += 1
        @show cnt
    end
    c
end
```

If you guessed 1076 you would be correct, where as `Bisection()` takes 55. Now almost all inputs won't be so extreme, but there isn't really a downside to guarding against them, save for a small performance boost if when we initialize we ensure the bracket [a,b] has a and b with the same sign. That's where the value gets lost, as we don't log until after initializing the state.

**Comment by KronosTheLate** [comment] 2022-03-25 19:59
Very interesting - I have not concidered how macjine precision makes Bisection guarantee the solution in so few iterations. So there are clearly things I did not know in the gritty details here...

As for representing both large and small values, could they be rounded to e.g. 5 significant digits when displayed? This should ensure that all numbers get a good amount of "detail" when printed - at least as much as any human would care for.

Potentially a field 'sigdigits' could be added to 'Tracks', which would determine the number of significant digits used for printing. This would make the rounding more transparent/ovbious, while also allowing custumization of it.

**Comment by jverzani** [comment] 2022-03-25 20:07
The rounding to 5 is a problem when they are close together; the not rounding a problem when they are large or close to 0. I think I'll have to work out a switch between using `f` for floating point and `e` for exponential notation. Do you think adding a third line to show |b-a| would be of value? (I think it might.)
